### ISSUE TITLE
repeat_max_countにチェックがないので不正な繰り返し上限が登録されてしまう

### ISSUE THREAD

**Issue by tetsuya-ki** [tetsuya-ki/discord-reminderbot#28]
それでこういうエラーが発生して、Taskが中止されて、リマインドされない事態になっている気がする
今まで登録されちゃったものもあると思うので、printerメソッドの繰り返し回数チェックのところに、remind[8].isdecimal()みたいなチェックを追加しようかな

```python
2021-09-05 14:41:39,664@ asyncio [ERROR] default_exception_handler: Task exception was never retrieved
future: <Task finished name='Task-66' coro=<Loop._loop() done, defined at /opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'<' not supported between instances of 'int' and 'str'")>
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/runner/discord-reminderbot/cogs/remindercog.py", line 94, in printer
    if remind[8] is None or repeat_count < remind[8]:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by tetsuya-ki** [comment]
developブランチで修正済。masterに取り込まれたらクローズ。
