### ISSUE TITLE
Task再起動後、繰り返しリマインドのところでエラーが発生してしまう可能性がある

### ISSUE THREAD

**Issue by tetsuya-ki** [tetsuya-ki/discord-reminderbot#36]
int型なのにisdecimal()とか無いぞという至極当たり前のエラーが出たので、修正が必要
なんでいつもはエラーが出ないんだろう？

```python
2021-10-01 12:44:21,645@ reminderbot [INFO] check_printer_is_running: Taskが停止していたので再起動します。
2021-10-01 12:44:21,645@ asyncio [ERROR] default_exception_handler: Task exception was never retrieved
future: <Task finished name='Task-28' coro=<Loop._loop() done, defined at /opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py:88> exception=AttributeError("'int' object has no attribute 'isdecimal'")>
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/runner/discord-reminderbotaj/cogs/remindercog.py", line 117, in printer
    if remind[8] is None or (remind[8].isdecimal() and repeat_count < remind[8]):
AttributeError: 'int' object has no attribute 'isdecimal'
```

**Comment by tetsuya-ki** [comment]
なぜかずっと放置してたけど、そろそろ直したい気持ちがある(でも最近エラー見かけないような？)

この辺りの奴ら。悪影響はないと思うしやってもいいはず
https://github.com/tetsuya-ki/discord-reminderbot/blob/1d5e2245f417395e2c843c93e468949b78b9047a/cogs/remindercog.py#L117
