### ISSUE TITLE
Unknown Guildで落ちるバグ(Stickerの影響で発生)

### ISSUE THREAD

**Issue by tetsuya-ki** [tetsuya-ki/discord-reminderbot#68]
## 原因

```python
# Sticker取得のため、ギルドの取得
guild = await self.bot.fetch_guild(remind[2])
```

- fetch_guildメソッドで例外が発生したが、try-catchされていないためbackground task 'printer'が終了

## エラーログ

```python
2023-05-19 20:35:24,659@ discord.ext.tasks [ERROR] _error: Unhandled exception in internal background task 'printer'.
Traceback (most recent call last):
  File "/home/ubuntu/python/discord-reminderbotpublic3/.venv/lib/python3.10/site-packages/discord/ext/tasks/init.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/ubuntu/python/discord-reminderbotpublic3/cogs/remindercog.py", line 70, in printer
    guild = await self.bot.fetch_guild(remind[2])
  File "/home/ubuntu/python/discord-reminderbotpublic3/.venv/lib/python3.10/site-packages/discord/client.py", line 2246, in fetch_guild
    data = await self.http.get_guild(guild_id, with_counts=with_counts)
  File "/home/ubuntu/python/discord-reminderbotpublic3/.venv/lib/python3.10/site-packages/discord/http.py", line 740, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10004)
```

**Comment by tetsuya-ki** [comment]
- 毎回try-catchしてなくてエラー発生させている気がする
- こう直す予定(コメント適当かも)

```ptyhon
                    # Sticker取得のため、ギルドの取得
                    try:
                        guild = await self.bot.fetch_guild(remind[2])
                        # ギルドのStickerの数だけ繰り返す
                        for sticker in guild.stickers:
                            # 文章にStickerが含まれていれば、Stickerリストに追加し、文章から削除
                            if re.search(f':{sticker.name}:', msg, flags=re.IGNORECASE):
                                sticker_list.append(sticker)
                                msg = re.sub(f' *<?:{sticker.name}:(\d*)>? *', '', msg, flags=re.IGNORECASE)
                                if len(sticker_list) >= 3:
                                    break
                    except:
                        msg = f'＊＊＊ギルド:{remind[2]}の取得({remind[4]})に失敗しました！＊＊＊'
                        LOG.error(msg)

                        # リマインドを削除
                        try:
                            await self.remind.update_status(remind[0], remind[2], self.remind.STATUS_ERROR)
                        except:
                            LOG.warning('リマインドを削除(フェッチ失敗/CH)/update中に失敗(ギルド内チャンネルのフェッチに失敗)')
                            continue
                        # 通知失敗について連絡
                        try:
                            get_control_channel = discord.utils.get(self.bot.get_all_channels(),guild__id=remind[2],name=self.remind.REMIND_CONTROL_CHANNEL)
                            remind_msg = await get_control_channel.send(f'@here No.{remind[0]}は権限不足などの原因でリマインドできませんでした。リマインドしたい場合は、投稿先チャンネルの設定見直しをお願いします\n> {remind[5]}')
                        except:
                            msg = f'＊＊＊さらに、{remind[2]}のチャンネル({self.remind.REMIND_CONTROL_CHANNEL})への投稿に失敗しました(フェッチ失敗投稿後)！＊＊＊'
                            LOG.error(msg)
                            continue
```
